// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vizsga_alap_backend.Models;

#nullable disable

namespace vizsga_alap_backend.Migrations
{
    [DbContext(typeof(VizsgaContext))]
    partial class VizsgaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("vizsga_alap_backend.Models.Kategorium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kategorianev")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("kategorianev");

                    b.Property<DateTime?>("Timestamps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("timestamps")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__kategori__3213E83F99093144");

                    b.ToTable("kategoria", (string)null);
                });

            modelBuilder.Entity("vizsga_alap_backend.Models.Teszt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Helyes")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("helyes");

                    b.Property<int>("KategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("kategoriaId");

                    b.Property<string>("Kerdes")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("kerdes");

                    b.Property<DateTime?>("Timestamps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("timestamps")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("V1")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("v1");

                    b.Property<string>("V2")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("v2");

                    b.Property<string>("V3")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("v3");

                    b.Property<string>("V4")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("v4");

                    b.HasKey("Id")
                        .HasName("PK__teszt__3213E83F12B8AC52");

                    b.HasIndex("KategoriaId");

                    b.ToTable("teszt", null, t =>
                        {
                            t.HasTrigger("alapHelyesValasz");
                        });
                });

            modelBuilder.Entity("vizsga_alap_backend.Models.Teszt", b =>
                {
                    b.HasOne("vizsga_alap_backend.Models.Kategorium", "Kategoria")
                        .WithMany("Teszts")
                        .HasForeignKey("KategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK__teszt__timestamp__3A81B327");

                    b.Navigation("Kategoria");
                });

            modelBuilder.Entity("vizsga_alap_backend.Models.Kategorium", b =>
                {
                    b.Navigation("Teszts");
                });
#pragma warning restore 612, 618
        }
    }
}
